### ISSUE TITLE
ChatControl Pro nullpointer

### ISSUE THREAD

**Issue by DynamicThijs** [Rexcantor/MultiLanguagePlugin#14] opened 2017-06-18 11:27 UTC
Hey there! I have just purchased your plugin, it's great! However, when someone types a message containing the [lang][/lang] brackets, I get a nullpointerexception. The same is for /tell, /msg etc.. (all commands handled by ChatControl).

The error: https://pastebin.com/jgrVsx9Q

**Comment by Rexcantor** [comment] 2017-06-18 11:41
Hey @DynamicThijs!
Thanks for contacting me. The error you sent me is associated with some weird chat modification. Probably ChatControl is changing the way messages are sent.  
Can you try to remove ChatControl and see if the issue is still there?

I'll fix it anyway, but it's just to make sure what's causing the error.

Thanks,
Rexcantor64

**Comment by DynamicThijs** [comment] 2017-06-18 12:33
Hey, the error is not present without ChatControl. With ChatControl enabled, you would just see "[lang]test[/lang]" for example, but without ChatControl it shows: "ERROR 404: message not found: test!".
 So ChatControl is overriding your plugin's chat manager, isn't it?

**Comment by Rexcantor** [comment] 2017-06-18 12:43
Do you have ChatControl free or premium?

**Comment by DynamicThijs** [comment] 2017-06-18 12:43
Premium

**Comment by Rexcantor** [comment] 2017-06-18 12:45
Ok. I'll see if I it the issue exists on the free version (would be great if you could test that for me, I'm on my phone right now). I'll fix it tomorrow or Tuesday. Today is impossible for me to access my computer.

**Comment by DynamicThijs** [comment] 2017-06-18 12:46
Ah ok, do you know what the listener priority is of MLP's chat handler?

**Comment by Rexcantor** [comment] 2017-06-18 12:49
My plugin intercepts Spigot packet handler, meaning it is placed right before the packets are sent to the client. It occurs after all listeners. But looks like ChatControl is doing the same thing OR it is changing the packets it a way that is not normal.  
I can only give you a detailed report after a research.

**Comment by DynamicThijs** [comment] 2017-06-18 12:50
OK, I've tested the free version and it's not affected. The Pro version of chatcontrol has an interactive chat view though with hover items. Might that be the problem?

**Comment by DynamicThijs** [comment] 2017-06-18 12:57
Actually, every chat message (no matter if the lang brackets are in) is affected by the nullpointer.

**Comment by Rexcantor** [comment] 2017-06-18 13:15
Yeah, protocol lib may be causing the issue.

**Comment by Rexcantor** [comment] 2017-06-18 13:16
Can you add me on Discord? Rexcantor64#7413

**Comment by DynamicThijs** [comment] 2017-06-18 13:26
Oh I don't have Discord. ProtocolLib is only being used for the packet rewriter though, not the chat formatter.

**Comment by Rexcantor** [comment] 2017-06-18 13:30
Looks like I found it:

![Packet Rules](https://i.imgur.com/NwlfJcw_d.jpg?maxwidth=640&shape=thumb&fidelity=high)


Add me on Skype then... live:rexcanntor64

**Comment by DynamicThijs** [comment] 2017-06-18 13:31
Added you on Skype

**Comment by Rexcantor** [comment] 2017-06-19 15:29
Fixed on [0.3.1](https://www.spigotmc.org/resources/multilanguageplugin-9.30331/update?update=169177)! Thanks for reporting it!

**Closed by Rexcantor** 2017-06-19 15:29 UTC
Labels: bug
